### ISSUE TITLE
Layout changes and setting modifications

### ISSUE THREAD

**Issue by andyluak** [MachoThemes/modula-seo#7]
1.  -Remove the current Add to Empty Alt and Add to Already Defined alt attributes . 
2.  - Leave the option with Custom Placeholders 
3. -First setting will be chosing the separator 
4. - Second setting will be renamed to Image Alt Attributes, that will be  input , from which the user will be able to chose either predefined placeholders ( %%sitetitle%% etc ) or just type the attributes that he wants . 
5. - Add a new placeholder %%alt%% which holds the value of the current alt ( if the user chooses to use his old alt attribute ) 
6. - Underneath the placeholder add a new checkbox : 
         -  Define for images that have alt attribute

      
7. - In the gallery settings in the modal , display a live preview of the alt the user has defined in SEO  . 
8. - Remove custom alt in edit post

**Comment by giucu91** [comment]
Trebuie adaugat in Modula lite hook ca sa poti face asta, daca a fost, nu mai este.

**Comment by giucu91** [comment]
O sa il inchid pe asta si o sa ramana #5
